In [10]:
import numpy as np
import pandas as pd
df=pd.read_csv('train.csv',na_values={'Cabin':0},index_col='PassengerId')
df.drop('Name',inplace=True,axis=1)
df.head()

Survived  Pclass     Sex   Age  SibSp  Parch            Ticket  \
PassengerId                                                                   
1                   0       3    male  22.0      1      0         A/5 21171   
2                   1       1  female  38.0      1      0          PC 17599   
3                   1       3  female  26.0      0      0  STON/O2. 3101282   
4                   1       1  female  35.0      1      0            113803   
5                   0       3    male  35.0      0      0            373450   

                Fare Cabin Embarked  
PassengerId                          
1             7.2500   NaN        S  
2            71.2833   C85        C  
3             7.9250   NaN        S  
4            53.1000  C123        S  
5             8.0500   NaN        S

In [27]:
x=df.drop(['SibSp','Survived','Parch','Embarked','Ticket'],axis=1)
x.head()
y=df['Survived']
y.head()

PassengerId
1    0
2    1
3    1
4    1
5    0
Name: Survived, dtype: int64

In [28]:
df['Sex'].value_counts()

male      577
female    314
Name: Sex, dtype: int64

In [29]:
x.replace({'Cabin':np.NaN,'Sex':'male'},0,inplace=True)
x.replace({'Sex':'female'},1,inplace=True)
x.head()

Pclass  Sex   Age     Fare Cabin
PassengerId                                  
1                 3    0  22.0   7.2500     0
2                 1    1  38.0  71.2833   C85
3                 3    1  26.0   7.9250     0
4                 1    1  35.0  53.1000  C123
5                 3    0  35.0   8.0500     0

In [30]:
median=x['Age'].median()
x['Age'].fillna(median,inplace=True)
x['Cabin'][x['Cabin']!=0]=1
x.head()

<ipython-input-30-d1fb9255f76a>:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  x['Cabin'][x['Cabin']!=0]=1


Pclass  Sex   Age     Fare Cabin
PassengerId                                  
1                 3    0  22.0   7.2500     0
2                 1    1  38.0  71.2833     1
3                 3    1  26.0   7.9250     0
4                 1    1  35.0  53.1000     1
5                 3    0  35.0   8.0500     0

In [31]:
print(x.corr())

          Pclass       Sex       Age      Fare
Pclass  1.000000 -0.131900 -0.339898 -0.549500
Sex    -0.131900  1.000000 -0.081163  0.182333
Age    -0.339898 -0.081163  1.000000  0.096688
Fare   -0.549500  0.182333  0.096688  1.000000


In [32]:
X=x.values
Y=y.values

In [33]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.3, random_state = 1)

In [34]:
print(X_train)
print(len(X_train))
print(X_test)
print(len(X_test))

[[3 1 17.0 14.4583 0]
 [2 1 28.0 24.0 0]
 [3 0 28.0 7.8958 0]
 ...
 [2 0 21.0 73.5 0]
 [3 1 28.0 7.55 0]
 [3 0 21.0 8.05 0]]
623
[[1 1 48.0 25.9292 1]
 [3 0 28.0 7.8958 0]
 [2 1 17.0 10.5 0]
 ...
 [2 0 33.0 12.275 0]
 [1 0 25.0 91.0792 1]
 [1 0 46.0 61.175 1]]
268


In [35]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train[:,2:5] = sc.fit_transform(X_train[:, 2:5])
X_test[:, 2:5] = sc.transform(X_test[:, 2:5])

In [36]:
X_train

array([[3, 1, -0.9525287424155243, -0.3579316081179839,
        -0.5259651549887092],
       [2, 1, -0.12477329329384186, -0.15279730197418076,
        -0.5259651549887092],
       [3, 0, -0.12477329329384186, -0.499016937154603,
        -0.5259651549887092],
       ...,
       [2, 0, -0.6515267609167307, 0.9113891799020317,
        -0.5259651549887092],
       [3, 1, -0.12477329329384186, -0.5064511934259726,
        -0.5259651549887092],
       [3, 0, -0.6515267609167307, -0.49570183502318255,
        -0.5259651549887092]], dtype=object)

In [38]:
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors = 5, metric = 'minkowski', p = 2)
classifier.fit(X_train, Y_train)

KNeighborsClassifier()

In [39]:
Y_pred = classifier.predict(X_test)
print(np.concatenate((Y_pred.reshape(len(Y_pred),1), Y_test.reshape(len(Y_test),1)),1))

[[1 1]
 [0 0]
 [1 1]
 [1 0]
 [1 1]
 [0 0]
 [1 0]
 [1 1]
 [1 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [0 1]
 [1 1]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 0]
 [0 1]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [0 1]
 [1 0]
 [0 0]
 [0 0]
 [0 1]
 [1 1]
 [0 0]
 [0 1]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 1]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [0 1]
 [0 1]
 [0 1]
 [0 1]
 [1 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [0 1]
 [0 0]
 [0 1]
 [0 0]
 [0 1]
 [1 1]
 [0 1]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [0 1]
 [1 0]
 [0 0]
 [1 1]

In [40]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(Y_test, Y_pred)
print(cm)
accuracy_score(Y_test, Y_pred)

[[138  15]
 [ 43  72]]


0.7835820895522388

In [41]:
from sklearn.ensemble import RandomForestClassifier
classifier2 = RandomForestClassifier(n_estimators = 10, criterion = 'entropy', random_state = 0)
classifier2.fit(X_train, Y_train)

RandomForestClassifier(criterion='entropy', n_estimators=10, random_state=0)

In [43]:
Y_pred2 = classifier2.predict(X_test)
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(Y_test, Y_pred2)
print(cm)
accuracy_score(Y_test, Y_pred2)

[[141  12]
 [ 44  71]]


0.7910447761194029